#!/bin/bash

function dev(){
    npx snowpack
    export-sprites
    npx servor . index.html 8080
}

function deploy(){
    mkdir -p dist
    rm -fr ./dist/*

    cp index.html ./dist/index.html
    cp manifest.json ./dist/manifest.json
    cp -r web_modules ./dist/
    cp *.js ./dist/
    cp -r services ./dist/
    cp -r data ./dist/
    cp -r assets ./dist/
    cp -r snd ./dist

    pushd dist
        aws s3 sync . s3://ld46.james-forbes.com --profile admin
        aws s3 cp index.html s3://ld46.james-forbes.com/index.html --profile admin
    popd

}

function export-sprites(){
    mkdir -p ./assets
    rm -fr ./assets/*

    ./tools/aseprite/Aseprite.exe \
        --split-layers \
        -b ./sprites/*.aseprite \
        --sheet ./assets/sheet.png \
        --data ./assets/frames.json \
        --list-layers \
        --list-tags \
        --list-tags \
        --filename-format '{"layer": "{layer}", "tag": "{tag}", "title": "{title}", "frameNumber": {frame1}}' \
        --format json-array \
        --all-layers

    cp ./sprites/splash3.jpg ./assets/splash3.jpg
}

function ...(){
    npx snowpack \
    && export-sprites \
    && git add -A && git commit -m "..." && git push \
    && bash run deploy
}

eval "$@"
