#!/bin/bash

function export-sprites(){
    mkdir -p ./assets
    rm -fr ./assets/*

    ./tools/aseprite/Aseprite.exe \
        --split-layers \
        -b ./sprites/*.aseprite \
        --sheet ./assets/sheet.png \
        --data ./assets/frames.json \
        --list-layers \
        --list-tags \
        --list-tags \
        --filename-format '{"layer": "{layer}", "title": "{title}", "frame": {frame1}}' \
        --format json-array \
        --all-layers
}

eval "$@"